[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/word/*"
  to = "/word/:splat.html"
  status = 200

[[redirects]]
  from = "/english/*"
  to = "/english/:splat.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404